"""Typed models used by the Python engine."""

from backend.engine.models.catalog import (
    EnemyCatalogResponse,
    EnemyPresetCatalogEntry,
    EnemyPresetUnitCatalogEntry,
    EnemyVariantCatalogEntry,
    PlayerCatalogResponse,
    PlayerClassCatalogEntry,
    PlayerLoadoutCatalogEntry,
    PlayerPresetCatalogEntry,
    PlayerPresetUnitCatalogEntry,
)
from backend.engine.models.state import (
    BatchCombinationSummary,
    BatchSummary,
    CombatEvent,
    DamageCandidate,
    DamageDetails,
    EncounterConfig,
    EncounterState,
    EncounterSummary,
    GridPosition,
    ReplayFrame,
    RunEncounterResult,
    StepEncounterResult,
    TerrainFeature,
    UnitState,
)

__all__ = [
    "BatchCombinationSummary",
    "BatchSummary",
    "CombatEvent",
    "DamageCandidate",
    "DamageDetails",
    "EnemyCatalogResponse",
    "EnemyPresetCatalogEntry",
    "EnemyPresetUnitCatalogEntry",
    "EnemyVariantCatalogEntry",
    "PlayerCatalogResponse",
    "PlayerClassCatalogEntry",
    "PlayerLoadoutCatalogEntry",
    "PlayerPresetCatalogEntry",
    "PlayerPresetUnitCatalogEntry",
    "EncounterConfig",
    "EncounterState",
    "EncounterSummary",
    "GridPosition",
    "ReplayFrame",
    "RunEncounterResult",
    "StepEncounterResult",
    "TerrainFeature",
    "UnitState",
]
