from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DamageComponentExpectation:
    damage_type: str
    damage_dice: tuple[tuple[int, int], ...] = ()
    damage_modifier: int = 0


@dataclass(frozen=True)
class AttackExpectation:
    kind: str
    attack_bonus: int
    ability_modifier: int
    damage_modifier: int
    damage_type: str | None
    reach: int | None = None
    range: tuple[int, int] | None = None
    damage_dice: tuple[tuple[int, int], ...] = ()
    advantage_damage_dice: tuple[tuple[int, int], ...] = ()
    damage_components: tuple[DamageComponentExpectation, ...] = ()
    advantage_damage_components: tuple[DamageComponentExpectation, ...] = ()
    advantage_against_self_grappled_target: bool = False
    selectable_damage_types: tuple[str, ...] = ()


@dataclass(frozen=True)
class MonsterExpectation:
    ai_profile_id: str
    max_hp: int
    ac: int
    speed: int
    initiative_mod: int
    passive_perception: int
    size_category: str
    footprint: tuple[int, int]
    ability_mods: dict[str, int]
    trait_ids: tuple[str, ...]
    attacks: dict[str, AttackExpectation]
    opening_weapon_id: str
    melee_fallback_weapon_id: str
    special_mechanics: tuple[str, ...]
    benchmark_preset_id: str
    benchmark_count: int
    role_tags: tuple[str, ...] = ()
    bonus_action_ids: tuple[str, ...] = ()
    reaction_ids: tuple[str, ...] = ("opportunity_attack",)
    damage_resistances: tuple[str, ...] = ()
    damage_immunities: tuple[str, ...] = ()
    damage_vulnerabilities: tuple[str, ...] = ()
    condition_immunities: tuple[str, ...] = ()
    creature_tags: tuple[str, ...] = ()
    resource_pools: tuple[tuple[str, int], ...] = ()


MONSTER_EXPECTATIONS: dict[str, MonsterExpectation] = {
    "hobgoblin_warrior": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=11,
        ac=18,
        speed=30,
        initiative_mod=3,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 1, "dex": 1, "con": 1, "int": 0, "wis": 0, "cha": -1},
        trait_ids=("pack_tactics",),
        attacks={
            "longsword": AttackExpectation(
                kind="melee",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="slashing",
                damage_dice=((2, 10),),
            )
        },
        opening_weapon_id="longsword",
        melee_fallback_weapon_id="longsword",
        special_mechanics=("pack_tactics",),
        benchmark_preset_id="hobgoblin_warrior_benchmark",
        benchmark_count=9,
    ),
    "hobgoblin_archer": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=11,
        ac=18,
        speed=30,
        initiative_mod=3,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 1, "dex": 1, "con": 1, "int": 0, "wis": 0, "cha": -1},
        trait_ids=("pack_tactics",),
        attacks={
            "longsword": AttackExpectation(
                kind="melee",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="slashing",
                damage_dice=((2, 10),),
            ),
            "longbow": AttackExpectation(
                kind="ranged",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="piercing",
                range=(150, 600),
                damage_dice=((1, 8),),
                advantage_damage_components=(DamageComponentExpectation("poison", ((3, 4),)),),
            ),
        },
        opening_weapon_id="longbow",
        melee_fallback_weapon_id="longsword",
        special_mechanics=("pack_tactics", "advantage_poison"),
        benchmark_preset_id="hobgoblin_archer_benchmark",
        benchmark_count=9,
    ),
    "hobgoblin_captain": MonsterExpectation(
        ai_profile_id="line_holder",
        max_hp=58,
        ac=17,
        speed=30,
        initiative_mod=4,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 2, "con": 2, "int": 1, "wis": 0, "cha": 1},
        trait_ids=("aura_of_authority",),
        attacks={
            "greatsword": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=0,
                damage_type=None,
                damage_components=(
                    DamageComponentExpectation("slashing", ((2, 6),), 2),
                    DamageComponentExpectation("poison", ((1, 6),), 0),
                ),
            ),
            "longbow": AttackExpectation(
                kind="ranged",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=0,
                damage_type=None,
                range=(150, 600),
                damage_components=(
                    DamageComponentExpectation("piercing", ((1, 8),), 2),
                    DamageComponentExpectation("poison", ((2, 4),), 0),
                ),
            ),
        },
        opening_weapon_id="greatsword",
        melee_fallback_weapon_id="greatsword",
        special_mechanics=("multiattack",),
        benchmark_preset_id="hobgoblin_captain_benchmark",
        benchmark_count=2,
    ),
    "deer": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=4,
        ac=13,
        speed=50,
        initiative_mod=3,
        passive_perception=14,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": 3, "con": 0, "int": -4, "wis": 2, "cha": -3},
        trait_ids=("agile",),
        attacks={
            "ram": AttackExpectation(
                kind="melee",
                attack_bonus=2,
                ability_modifier=0,
                damage_modifier=0,
                damage_type="bludgeoning",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="ram",
        melee_fallback_weapon_id="ram",
        special_mechanics=(),
        benchmark_preset_id="deer_benchmark",
        benchmark_count=15,
    ),
    "cat": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=2,
        ac=12,
        speed=40,
        initiative_mod=2,
        passive_perception=13,
        size_category="tiny",
        footprint=(1, 1),
        ability_mods={"str": -4, "dex": 2, "con": 0, "int": -4, "wis": 1, "cha": -2},
        trait_ids=("jumper",),
        attacks={
            "scratch": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=1,
                damage_type="slashing",
            )
        },
        opening_weapon_id="scratch",
        melee_fallback_weapon_id="scratch",
        special_mechanics=(),
        benchmark_preset_id="cat_benchmark",
        benchmark_count=15,
    ),
    "weasel": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=1,
        ac=13,
        speed=30,
        initiative_mod=3,
        passive_perception=13,
        size_category="tiny",
        footprint=(1, 1),
        ability_mods={"str": -4, "dex": 3, "con": -1, "int": -4, "wis": 1, "cha": -4},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=1,
                damage_type="piercing",
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=(),
        benchmark_preset_id="weasel_benchmark",
        benchmark_count=15,
    ),
    "badger": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=5,
        ac=11,
        speed=20,
        initiative_mod=0,
        passive_perception=13,
        size_category="tiny",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": 0, "con": 3, "int": -4, "wis": 1, "cha": -3},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=2,
                ability_modifier=0,
                damage_modifier=1,
                damage_type="piercing",
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=(),
        benchmark_preset_id="badger_benchmark",
        benchmark_count=15,
        damage_resistances=("poison",),
    ),
    "tough": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=32,
        ac=12,
        speed=30,
        initiative_mod=1,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 1, "con": 2, "int": 0, "wis": 0, "cha": 0},
        trait_ids=("pack_tactics",),
        attacks={
            "mace": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="bludgeoning",
                damage_dice=((1, 6),),
            ),
            "heavy_crossbow": AttackExpectation(
                kind="ranged",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="piercing",
                range=(100, 400),
                damage_dice=((1, 10),),
            ),
        },
        opening_weapon_id="heavy_crossbow",
        melee_fallback_weapon_id="mace",
        special_mechanics=("pack_tactics",),
        benchmark_preset_id="tough_benchmark",
        benchmark_count=3,
    ),
    "axe_beak": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=19,
        ac=11,
        speed=50,
        initiative_mod=1,
        passive_perception=10,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 2, "dex": 1, "con": 1, "int": -4, "wis": 0, "cha": -3},
        trait_ids=(),
        attacks={
            "beak": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="slashing",
                damage_dice=((1, 8),),
            )
        },
        opening_weapon_id="beak",
        melee_fallback_weapon_id="beak",
        special_mechanics=(),
        benchmark_preset_id="axe_beak_benchmark",
        benchmark_count=5,
    ),
    "draft_horse": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=15,
        ac=10,
        speed=40,
        initiative_mod=0,
        passive_perception=10,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 4, "dex": 0, "con": 2, "int": -4, "wis": 0, "cha": -2},
        trait_ids=(),
        attacks={
            "hooves": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="bludgeoning",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="hooves",
        melee_fallback_weapon_id="hooves",
        special_mechanics=(),
        benchmark_preset_id="draft_horse_benchmark",
        benchmark_count=7,
    ),
    "riding_horse": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=13,
        ac=11,
        speed=60,
        initiative_mod=1,
        passive_perception=10,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 3, "dex": 1, "con": 1, "int": -4, "wis": 0, "cha": -2},
        trait_ids=(),
        attacks={
            "hooves": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="bludgeoning",
                damage_dice=((1, 8),),
            )
        },
        opening_weapon_id="hooves",
        melee_fallback_weapon_id="hooves",
        special_mechanics=(),
        benchmark_preset_id="riding_horse_benchmark",
        benchmark_count=8,
    ),
    "cultist": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=9,
        ac=12,
        speed=30,
        initiative_mod=1,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": 1, "con": 0, "int": 0, "wis": 1, "cha": 0},
        trait_ids=(),
        attacks={
            "ritual_sickle": AttackExpectation(
                kind="melee",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=0,
                damage_type=None,
                damage_components=(
                    DamageComponentExpectation("slashing", ((1, 4),), 1),
                    DamageComponentExpectation("necrotic", (), 1),
                ),
            )
        },
        opening_weapon_id="ritual_sickle",
        melee_fallback_weapon_id="ritual_sickle",
        special_mechanics=("split_damage",),
        benchmark_preset_id="cultist_benchmark",
        benchmark_count=11,
    ),
    "warrior_infantry": MonsterExpectation(
        ai_profile_id="line_holder",
        max_hp=9,
        ac=13,
        speed=30,
        initiative_mod=0,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 1, "dex": 0, "con": 0, "int": -1, "wis": 0, "cha": -1},
        trait_ids=("pack_tactics",),
        attacks={
            "spear": AttackExpectation(
                kind="melee",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="piercing",
                damage_dice=((1, 6),),
            )
        },
        opening_weapon_id="spear",
        melee_fallback_weapon_id="spear",
        special_mechanics=("pack_tactics",),
        benchmark_preset_id="warrior_infantry_benchmark",
        benchmark_count=11,
    ),
    "camel": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=17,
        ac=10,
        speed=50,
        initiative_mod=-1,
        passive_perception=10,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 2, "dex": -1, "con": 3, "int": -4, "wis": 0, "cha": -3},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="bludgeoning",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=(),
        benchmark_preset_id="camel_benchmark",
        benchmark_count=6,
    ),
    "mule": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=11,
        ac=10,
        speed=40,
        initiative_mod=0,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 0, "con": 1, "int": -4, "wis": 0, "cha": -3},
        trait_ids=(),
        attacks={
            "hooves": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="bludgeoning",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="hooves",
        melee_fallback_weapon_id="hooves",
        special_mechanics=(),
        benchmark_preset_id="mule_benchmark",
        benchmark_count=9,
    ),
    "pony": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=11,
        ac=10,
        speed=40,
        initiative_mod=0,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 0, "con": 1, "int": -4, "wis": 0, "cha": -2},
        trait_ids=(),
        attacks={
            "hooves": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="bludgeoning",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="hooves",
        melee_fallback_weapon_id="hooves",
        special_mechanics=(),
        benchmark_preset_id="pony_benchmark",
        benchmark_count=9,
    ),
    "commoner": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=4,
        ac=10,
        speed=30,
        initiative_mod=0,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": 0, "con": 0, "int": 0, "wis": 0, "cha": 0},
        trait_ids=(),
        attacks={
            "club": AttackExpectation(
                kind="melee",
                attack_bonus=2,
                ability_modifier=0,
                damage_modifier=0,
                damage_type="bludgeoning",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="club",
        melee_fallback_weapon_id="club",
        special_mechanics=(),
        benchmark_preset_id="commoner_benchmark",
        benchmark_count=15,
    ),
    "hyena": MonsterExpectation(
        ai_profile_id="pack_hunter",
        max_hp=5,
        ac=11,
        speed=50,
        initiative_mod=1,
        passive_perception=13,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": 1, "con": 1, "int": -4, "wis": 1, "cha": -3},
        trait_ids=("pack_tactics",),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=2,
                ability_modifier=0,
                damage_modifier=0,
                damage_type="piercing",
                damage_dice=((1, 6),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=("pack_tactics",),
        benchmark_preset_id="hyena_benchmark",
        benchmark_count=15,
    ),
    "jackal": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=3,
        ac=12,
        speed=40,
        initiative_mod=2,
        passive_perception=15,
        size_category="small",
        footprint=(1, 1),
        ability_mods={"str": -1, "dex": 2, "con": 0, "int": -4, "wis": 1, "cha": -2},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=1,
                ability_modifier=-1,
                damage_modifier=-1,
                damage_type="piercing",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=(),
        benchmark_preset_id="jackal_benchmark",
        benchmark_count=15,
    ),
    "goblin_minion": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=7,
        ac=12,
        speed=30,
        initiative_mod=2,
        passive_perception=9,
        size_category="small",
        footprint=(1, 1),
        ability_mods={"str": -1, "dex": 2, "con": 0, "int": 0, "wis": -1, "cha": -1},
        trait_ids=("nimble_escape",),
        attacks={
            "dagger": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                damage_dice=((1, 4),),
            ),
            "dagger_throw": AttackExpectation(
                kind="ranged",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                range=(20, 60),
                damage_dice=((1, 4),),
            ),
        },
        opening_weapon_id="dagger_throw",
        melee_fallback_weapon_id="dagger",
        special_mechanics=("nimble_escape",),
        benchmark_preset_id="goblin_minion_benchmark",
        benchmark_count=14,
        bonus_action_ids=("disengage",),
    ),
    "kobold_warrior": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=7,
        ac=14,
        speed=30,
        initiative_mod=2,
        passive_perception=8,
        size_category="small",
        footprint=(1, 1),
        ability_mods={"str": -2, "dex": 2, "con": -1, "int": -1, "wis": -2, "cha": -1},
        trait_ids=("pack_tactics", "sunlight_sensitivity"),
        attacks={
            "dagger": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                damage_dice=((1, 4),),
            ),
            "dagger_throw": AttackExpectation(
                kind="ranged",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                range=(20, 60),
                damage_dice=((1, 4),),
            ),
        },
        opening_weapon_id="dagger_throw",
        melee_fallback_weapon_id="dagger",
        special_mechanics=("pack_tactics", "sunlight_sensitivity"),
        benchmark_preset_id="kobold_warrior_benchmark",
        benchmark_count=14,
    ),
    "kobold_scale_sorcerer": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=27,
        ac=15,
        speed=30,
        initiative_mod=2,
        passive_perception=9,
        size_category="small",
        footprint=(1, 1),
        ability_mods={"str": -2, "dex": 2, "con": 2, "int": 0, "wis": -1, "cha": 2},
        trait_ids=("pack_tactics", "sunlight_sensitivity"),
        attacks={
            "dagger": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                damage_dice=((1, 4),),
            ),
            "dagger_throw": AttackExpectation(
                kind="ranged",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                range=(20, 60),
                damage_dice=((1, 4),),
            ),
            "chromatic_bolt": AttackExpectation(
                kind="ranged",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="acid",
                range=(60, 60),
                damage_dice=((2, 6),),
                selectable_damage_types=("acid", "cold", "fire", "lightning", "poison", "thunder"),
            ),
        },
        opening_weapon_id="chromatic_bolt",
        melee_fallback_weapon_id="dagger",
        special_mechanics=("pack_tactics", "selectable_damage", "sunlight_sensitivity"),
        benchmark_preset_id="kobold_scale_sorcerer_benchmark",
        benchmark_count=4,
        role_tags=("caster",),
    ),
    "skeleton": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=13,
        ac=14,
        speed=30,
        initiative_mod=3,
        passive_perception=9,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": 3, "con": 2, "int": -2, "wis": -1, "cha": -3},
        trait_ids=(),
        attacks={
            "shortsword": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="piercing",
                damage_dice=((1, 6),),
            ),
            "shortbow": AttackExpectation(
                kind="ranged",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="piercing",
                range=(80, 320),
                damage_dice=((1, 6),),
            ),
        },
        opening_weapon_id="shortbow",
        melee_fallback_weapon_id="shortsword",
        special_mechanics=(),
        damage_immunities=("poison",),
        damage_vulnerabilities=("bludgeoning",),
        benchmark_preset_id="skeleton_benchmark",
        benchmark_count=8,
        creature_tags=("undead",),
    ),
    "zombie": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=15,
        ac=8,
        speed=20,
        initiative_mod=-2,
        passive_perception=8,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 1, "dex": -2, "con": 3, "int": -4, "wis": -2, "cha": -3},
        trait_ids=("undead_fortitude",),
        attacks={
            "slam": AttackExpectation(
                kind="melee",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="bludgeoning",
                damage_dice=((1, 8),),
            )
        },
        opening_weapon_id="slam",
        melee_fallback_weapon_id="slam",
        special_mechanics=("undead_fortitude",),
        damage_immunities=("poison",),
        benchmark_preset_id="zombie_benchmark",
        benchmark_count=7,
        creature_tags=("undead",),
    ),
    "ogre_zombie": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=85,
        ac=8,
        speed=30,
        initiative_mod=-2,
        passive_perception=8,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 4, "dex": -2, "con": 4, "int": -4, "wis": -2, "cha": -3},
        trait_ids=("undead_fortitude",),
        attacks={
            "slam": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="bludgeoning",
                damage_dice=((2, 8),),
            )
        },
        opening_weapon_id="slam",
        melee_fallback_weapon_id="slam",
        special_mechanics=("undead_fortitude",),
        damage_immunities=("poison",),
        benchmark_preset_id="ogre_zombie_benchmark",
        benchmark_count=1,
        creature_tags=("undead",),
    ),
    "warhorse_skeleton": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=22,
        ac=13,
        speed=60,
        initiative_mod=1,
        passive_perception=9,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 4, "dex": 1, "con": 2, "int": -4, "wis": -1, "cha": -3},
        trait_ids=(),
        attacks={
            "hooves": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="bludgeoning",
                damage_dice=((1, 6),),
            ),
        },
        opening_weapon_id="hooves",
        melee_fallback_weapon_id="hooves",
        special_mechanics=("prone_on_hit",),
        damage_immunities=("poison",),
        damage_vulnerabilities=("bludgeoning",),
        condition_immunities=("exhaustion", "poisoned"),
        benchmark_preset_id="warhorse_skeleton_benchmark",
        benchmark_count=5,
        creature_tags=("undead",),
    ),
    "giant_rat": MonsterExpectation(
        ai_profile_id="pack_hunter",
        max_hp=7,
        ac=13,
        speed=30,
        initiative_mod=3,
        passive_perception=12,
        size_category="small",
        footprint=(1, 1),
        ability_mods={"str": -2, "dex": 3, "con": 0, "int": -4, "wis": 0, "cha": -3},
        trait_ids=("pack_tactics",),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="piercing",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=("pack_tactics",),
        benchmark_preset_id="giant_rat_benchmark",
        benchmark_count=14,
    ),
    "giant_fire_beetle": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=4,
        ac=13,
        speed=30,
        initiative_mod=0,
        passive_perception=8,
        size_category="small",
        footprint=(1, 1),
        ability_mods={"str": -1, "dex": 0, "con": 1, "int": -5, "wis": -2, "cha": -4},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=1,
                ability_modifier=-1,
                damage_modifier=1,
                damage_type="fire",
                damage_dice=(),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=(),
        damage_resistances=("fire",),
        benchmark_preset_id="giant_fire_beetle_benchmark",
        benchmark_count=15,
    ),
    "giant_weasel": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=9,
        ac=13,
        speed=40,
        initiative_mod=3,
        passive_perception=13,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": 3, "con": 0, "int": -3, "wis": 1, "cha": -3},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="piercing",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=(),
        benchmark_preset_id="giant_weasel_benchmark",
        benchmark_count=11,
    ),
    "worg": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=26,
        ac=13,
        speed=50,
        initiative_mod=1,
        passive_perception=14,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 3, "dex": 1, "con": 1, "int": -2, "wis": 0, "cha": -1},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="piercing",
                damage_dice=((1, 8),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=("harry_target",),
        benchmark_preset_id="worg_benchmark",
        benchmark_count=4,
    ),
    "animated_armor": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=33,
        ac=18,
        speed=25,
        initiative_mod=2,
        passive_perception=6,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 0, "con": 1, "int": -5, "wis": -4, "cha": -5},
        trait_ids=(),
        attacks={
            "slam": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="bludgeoning",
                damage_dice=((1, 6),),
            )
        },
        opening_weapon_id="slam",
        melee_fallback_weapon_id="slam",
        special_mechanics=("multiattack",),
        damage_immunities=("poison", "psychic"),
        benchmark_preset_id="animated_armor_benchmark",
        benchmark_count=3,
    ),
    "dire_wolf": MonsterExpectation(
        ai_profile_id="pack_hunter",
        max_hp=22,
        ac=14,
        speed=50,
        initiative_mod=2,
        passive_perception=15,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 3, "dex": 2, "con": 2, "int": -4, "wis": 1, "cha": -2},
        trait_ids=("pack_tactics",),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="piercing",
                damage_dice=((1, 10),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=("pack_tactics", "prone_on_hit"),
        benchmark_preset_id="dire_wolf_benchmark",
        benchmark_count=5,
    ),
    "awakened_shrub": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=10,
        ac=9,
        speed=20,
        initiative_mod=-1,
        passive_perception=10,
        size_category="small",
        footprint=(1, 1),
        ability_mods={"str": -4, "dex": -1, "con": 0, "int": 0, "wis": 0, "cha": -2},
        trait_ids=(),
        attacks={
            "rake": AttackExpectation(
                kind="melee",
                attack_bonus=1,
                ability_modifier=-1,
                damage_modifier=1,
                damage_type="slashing",
                damage_dice=(),
            )
        },
        opening_weapon_id="rake",
        melee_fallback_weapon_id="rake",
        special_mechanics=(),
        damage_resistances=("piercing",),
        damage_vulnerabilities=("fire",),
        benchmark_preset_id="awakened_shrub_benchmark",
        benchmark_count=10,
    ),
    "awakened_tree": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=59,
        ac=13,
        speed=20,
        initiative_mod=-2,
        passive_perception=10,
        size_category="huge",
        footprint=(3, 3),
        ability_mods={"str": 4, "dex": -2, "con": 2, "int": 0, "wis": 0, "cha": -2},
        trait_ids=(),
        attacks={
            "slam": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="bludgeoning",
                reach=10,
                damage_dice=((3, 6),),
            )
        },
        opening_weapon_id="slam",
        melee_fallback_weapon_id="slam",
        special_mechanics=(),
        damage_resistances=("bludgeoning", "piercing"),
        damage_vulnerabilities=("fire",),
        benchmark_preset_id="awakened_tree_benchmark",
        benchmark_count=2,
    ),
    "lemure": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=9,
        ac=9,
        speed=20,
        initiative_mod=-3,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": -3, "con": 0, "int": -5, "wis": 0, "cha": -4},
        trait_ids=(),
        attacks={
            "vile_slime": AttackExpectation(
                kind="melee",
                attack_bonus=2,
                ability_modifier=0,
                damage_modifier=0,
                damage_type="poison",
                damage_dice=((1, 4),),
            )
        },
        opening_weapon_id="vile_slime",
        melee_fallback_weapon_id="vile_slime",
        special_mechanics=(),
        damage_resistances=("cold",),
        damage_immunities=("fire", "poison"),
        benchmark_preset_id="lemure_benchmark",
        benchmark_count=11,
    ),
    "ogre": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=68,
        ac=11,
        speed=40,
        initiative_mod=-1,
        passive_perception=8,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 4, "dex": -1, "con": 3, "int": -3, "wis": -2, "cha": -2},
        trait_ids=(),
        attacks={
            "greatclub": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="bludgeoning",
                damage_dice=((2, 8),),
            ),
            "javelin": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="piercing",
                damage_dice=((2, 6),),
            ),
            "javelin_throw": AttackExpectation(
                kind="ranged",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="piercing",
                range=(30, 120),
                damage_dice=((2, 6),),
            ),
        },
        opening_weapon_id="javelin_throw",
        melee_fallback_weapon_id="greatclub",
        special_mechanics=(),
        benchmark_preset_id="ogre_benchmark",
        benchmark_count=1,
    ),
    "ape": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=19,
        ac=12,
        speed=30,
        initiative_mod=2,
        passive_perception=13,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 3, "dex": 2, "con": 2, "int": -2, "wis": 1, "cha": -2},
        trait_ids=(),
        attacks={
            "fist": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="bludgeoning",
                damage_dice=((1, 4),),
            ),
            "rock": AttackExpectation(
                kind="ranged",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="bludgeoning",
                range=(25, 50),
                damage_dice=((2, 6),),
            ),
        },
        opening_weapon_id="fist",
        melee_fallback_weapon_id="fist",
        special_mechanics=("multiattack",),
        benchmark_preset_id="ape_benchmark",
        benchmark_count=5,
    ),
    "centaur_trooper": MonsterExpectation(
        ai_profile_id="line_holder",
        max_hp=45,
        ac=16,
        speed=50,
        initiative_mod=2,
        passive_perception=13,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 4, "dex": 2, "con": 2, "int": -1, "wis": 1, "cha": 0},
        trait_ids=(),
        attacks={
            "pike": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="piercing",
                reach=10,
                damage_dice=((1, 10),),
            ),
            "longbow": AttackExpectation(
                kind="ranged",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                range=(150, 600),
                damage_dice=((1, 8),),
            ),
        },
        opening_weapon_id="pike",
        melee_fallback_weapon_id="pike",
        special_mechanics=("multiattack",),
        benchmark_preset_id="centaur_trooper_benchmark",
        benchmark_count=2,
    ),
    "black_bear": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=19,
        ac=11,
        speed=30,
        initiative_mod=1,
        passive_perception=15,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 1, "con": 2, "int": -4, "wis": 1, "cha": -2},
        trait_ids=(),
        attacks={
            "rend": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="slashing",
                damage_dice=((1, 6),),
            )
        },
        opening_weapon_id="rend",
        melee_fallback_weapon_id="rend",
        special_mechanics=("multiattack",),
        benchmark_preset_id="black_bear_benchmark",
        benchmark_count=5,
    ),
    "brown_bear": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=22,
        ac=11,
        speed=40,
        initiative_mod=1,
        passive_perception=13,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 3, "dex": 1, "con": 2, "int": -4, "wis": 1, "cha": -2},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="piercing",
                damage_dice=((1, 8),),
            ),
            "claw": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="slashing",
                damage_dice=((1, 4),),
            ),
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=("multiattack", "prone_on_hit"),
        benchmark_preset_id="brown_bear_benchmark",
        benchmark_count=5,
    ),
    "tiger": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=30,
        ac=13,
        speed=40,
        initiative_mod=3,
        passive_perception=13,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 3, "dex": 3, "con": 2, "int": -4, "wis": 1, "cha": -1},
        trait_ids=("nimble_escape",),
        attacks={
            "rend": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="slashing",
                damage_dice=((2, 6),),
            )
        },
        opening_weapon_id="rend",
        melee_fallback_weapon_id="rend",
        special_mechanics=("multiattack", "prone_on_hit", "nimble_escape"),
        benchmark_preset_id="tiger_benchmark",
        benchmark_count=3,
        bonus_action_ids=("disengage",),
    ),
    "saber_toothed_tiger": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=52,
        ac=13,
        speed=40,
        initiative_mod=3,
        passive_perception=15,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 4, "dex": 3, "con": 2, "int": -4, "wis": 1, "cha": -1},
        trait_ids=("nimble_escape",),
        attacks={
            "rend": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="slashing",
                damage_dice=((2, 6),),
            )
        },
        opening_weapon_id="rend",
        melee_fallback_weapon_id="rend",
        special_mechanics=("multiattack", "nimble_escape"),
        benchmark_preset_id="saber_toothed_tiger_benchmark",
        benchmark_count=2,
        bonus_action_ids=("disengage",),
    ),
    "owlbear": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=59,
        ac=13,
        speed=40,
        initiative_mod=1,
        passive_perception=15,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 5, "dex": 1, "con": 3, "int": -4, "wis": 1, "cha": -2},
        trait_ids=(),
        attacks={
            "rend": AttackExpectation(
                kind="melee",
                attack_bonus=7,
                ability_modifier=5,
                damage_modifier=5,
                damage_type="slashing",
                damage_dice=((2, 8),),
            )
        },
        opening_weapon_id="rend",
        melee_fallback_weapon_id="rend",
        special_mechanics=("multiattack",),
        benchmark_preset_id="owlbear_benchmark",
        benchmark_count=2,
    ),
    "ankylosaurus": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=68,
        ac=15,
        speed=30,
        initiative_mod=0,
        passive_perception=11,
        size_category="huge",
        footprint=(3, 3),
        ability_mods={"str": 4, "dex": 0, "con": 2, "int": -4, "wis": 1, "cha": -3},
        trait_ids=(),
        attacks={
            "tail": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="bludgeoning",
                reach=10,
                damage_dice=((1, 10),),
            )
        },
        opening_weapon_id="tail",
        melee_fallback_weapon_id="tail",
        special_mechanics=("multiattack", "prone_on_hit"),
        benchmark_preset_id="ankylosaurus_benchmark",
        benchmark_count=1,
    ),
    "archelon": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=90,
        ac=17,
        speed=20,
        initiative_mod=3,
        passive_perception=12,
        size_category="huge",
        footprint=(3, 3),
        ability_mods={"str": 4, "dex": 3, "con": 1, "int": -3, "wis": 2, "cha": -2},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="piercing",
                damage_dice=((3, 6),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=("multiattack",),
        benchmark_preset_id="archelon_benchmark",
        benchmark_count=1,
    ),
    "grick": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=54,
        ac=14,
        speed=30,
        initiative_mod=2,
        passive_perception=12,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 2, "con": 0, "int": -4, "wis": 2, "cha": -3},
        trait_ids=(),
        attacks={
            "beak": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                damage_dice=((2, 6),),
            ),
            "tentacles": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="slashing",
                damage_dice=((1, 10),),
            ),
        },
        opening_weapon_id="beak",
        melee_fallback_weapon_id="beak",
        special_mechanics=("multiattack", "grapple_on_hit"),
        benchmark_preset_id="grick_benchmark",
        benchmark_count=2,
    ),
    "griffon": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=59,
        ac=12,
        speed=30,
        initiative_mod=2,
        passive_perception=15,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 4, "dex": 2, "con": 3, "int": -4, "wis": 1, "cha": -1},
        trait_ids=("opening_flight_landing",),
        attacks={
            "rend": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="piercing",
                damage_dice=((1, 8),),
            )
        },
        opening_weapon_id="rend",
        melee_fallback_weapon_id="rend",
        special_mechanics=("multiattack", "grapple_on_hit", "opening_flight_landing"),
        benchmark_preset_id="griffon_benchmark",
        benchmark_count=2,
        resource_pools=(("opening_landing_uses", 1),),
    ),
    "hippopotamus": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=82,
        ac=14,
        speed=30,
        initiative_mod=-2,
        passive_perception=13,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 5, "dex": -2, "con": 2, "int": -4, "wis": 1, "cha": -3},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=7,
                ability_modifier=5,
                damage_modifier=5,
                damage_type="piercing",
                damage_dice=((2, 10),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=("multiattack",),
        benchmark_preset_id="hippopotamus_benchmark",
        benchmark_count=1,
    ),
    "berserker": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=67,
        ac=13,
        speed=30,
        initiative_mod=1,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 3, "dex": 1, "con": 3, "int": -1, "wis": 0, "cha": -1},
        trait_ids=("bloodied_frenzy",),
        attacks={
            "greataxe": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="slashing",
                damage_dice=((1, 12),),
            )
        },
        opening_weapon_id="greataxe",
        melee_fallback_weapon_id="greataxe",
        special_mechanics=("bloodied_frenzy",),
        benchmark_preset_id="berserker_benchmark",
        benchmark_count=1,
    ),
    "gnoll_warrior": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=27,
        ac=15,
        speed=30,
        initiative_mod=1,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 1, "con": 0, "int": -2, "wis": 0, "cha": -2},
        trait_ids=("rampage",),
        attacks={
            "rend": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                damage_dice=((1, 6),),
            ),
            "bone_bow": AttackExpectation(
                kind="ranged",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="piercing",
                range=(150, 600),
                damage_dice=((1, 10),),
            ),
        },
        opening_weapon_id="bone_bow",
        melee_fallback_weapon_id="rend",
        special_mechanics=("rampage",),
        benchmark_preset_id="gnoll_warrior_benchmark",
        benchmark_count=4,
        bonus_action_ids=("rampage",),
    ),
    "giant_hyena": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=45,
        ac=12,
        speed=50,
        initiative_mod=2,
        passive_perception=13,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 3, "dex": 2, "con": 2, "int": -4, "wis": 1, "cha": -2},
        trait_ids=("rampage",),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="piercing",
                damage_dice=((2, 6),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=("rampage",),
        benchmark_preset_id="giant_hyena_benchmark",
        benchmark_count=2,
        bonus_action_ids=("rampage",),
    ),
    "bandit_captain": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=52,
        ac=15,
        speed=30,
        initiative_mod=3,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 3, "con": 2, "int": 2, "wis": 0, "cha": 2},
        trait_ids=(),
        attacks={
            "captain_scimitar": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="slashing",
                damage_dice=((1, 6),),
            ),
            "pistol": AttackExpectation(
                kind="ranged",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="piercing",
                range=(30, 90),
                damage_dice=((1, 10),),
            ),
        },
        opening_weapon_id="pistol",
        melee_fallback_weapon_id="captain_scimitar",
        special_mechanics=("multiattack", "parry"),
        benchmark_preset_id="bandit_captain_benchmark",
        benchmark_count=2,
        reaction_ids=("opportunity_attack", "parry"),
    ),
    "goblin_boss": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=21,
        ac=17,
        speed=30,
        initiative_mod=2,
        passive_perception=9,
        size_category="small",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": 2, "con": 0, "int": 0, "wis": -1, "cha": 0},
        trait_ids=("nimble_escape",),
        attacks={
            "scimitar": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="slashing",
                damage_dice=((1, 6),),
                advantage_damage_dice=((1, 4),),
            ),
            "shortbow": AttackExpectation(
                kind="ranged",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                range=(80, 320),
                damage_dice=((1, 6),),
                advantage_damage_dice=((1, 4),),
            ),
        },
        opening_weapon_id="shortbow",
        melee_fallback_weapon_id="scimitar",
        special_mechanics=("multiattack", "nimble_escape", "redirect_attack", "advantage_damage"),
        benchmark_preset_id="goblin_boss_benchmark",
        benchmark_count=5,
        bonus_action_ids=("disengage",),
        reaction_ids=("opportunity_attack", "redirect_attack"),
    ),
    "bugbear_warrior": MonsterExpectation(
        ai_profile_id="grappling_brute",
        max_hp=33,
        ac=14,
        speed=30,
        initiative_mod=2,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 2, "dex": 2, "con": 1, "int": -1, "wis": 0, "cha": -1},
        trait_ids=(),
        attacks={
            "grab": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="bludgeoning",
                reach=10,
                damage_dice=((2, 6),),
            ),
            "light_hammer": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="bludgeoning",
                reach=10,
                damage_dice=((3, 4),),
                advantage_against_self_grappled_target=True,
            ),
            "light_hammer_throw": AttackExpectation(
                kind="ranged",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="bludgeoning",
                range=(20, 60),
                damage_dice=((3, 4),),
                advantage_against_self_grappled_target=True,
            ),
        },
        opening_weapon_id="grab",
        melee_fallback_weapon_id="light_hammer",
        special_mechanics=("grapple_on_hit", "grappled_target_advantage"),
        benchmark_preset_id="bugbear_warrior_benchmark",
        benchmark_count=3,
    ),
    "noble": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=9,
        ac=15,
        speed=30,
        initiative_mod=1,
        passive_perception=12,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 0, "dex": 1, "con": 0, "int": 1, "wis": 2, "cha": 3},
        trait_ids=(),
        attacks={
            "rapier": AttackExpectation(
                kind="melee",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="piercing",
                damage_dice=((1, 8),),
            )
        },
        opening_weapon_id="rapier",
        melee_fallback_weapon_id="rapier",
        special_mechanics=("parry",),
        benchmark_preset_id="noble_benchmark",
        benchmark_count=11,
        reaction_ids=("opportunity_attack", "parry"),
    ),
    "mastiff": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=5,
        ac=12,
        speed=40,
        initiative_mod=2,
        passive_perception=15,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 1, "dex": 2, "con": 1, "int": -4, "wis": 1, "cha": -2},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="piercing",
                damage_dice=((1, 6),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=("prone_on_hit",),
        benchmark_preset_id="mastiff_benchmark",
        benchmark_count=15,
    ),
    "giant_crab": MonsterExpectation(
        ai_profile_id="grappling_brute",
        max_hp=13,
        ac=15,
        speed=30,
        initiative_mod=1,
        passive_perception=9,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 1, "dex": 1, "con": 0, "int": -5, "wis": -1, "cha": -4},
        trait_ids=(),
        attacks={
            "claw": AttackExpectation(
                kind="melee",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="bludgeoning",
                damage_dice=((1, 6),),
            )
        },
        opening_weapon_id="claw",
        melee_fallback_weapon_id="claw",
        special_mechanics=("grapple_on_hit",),
        benchmark_preset_id="giant_crab_benchmark",
        benchmark_count=8,
    ),
    "giant_badger": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=15,
        ac=13,
        speed=30,
        initiative_mod=0,
        passive_perception=13,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 1, "dex": 0, "con": 3, "int": -4, "wis": 1, "cha": -3},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="piercing",
                damage_dice=((2, 4),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=(),
        benchmark_preset_id="giant_badger_benchmark",
        benchmark_count=7,
        damage_resistances=("poison",),
    ),
    "giant_lizard": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=19,
        ac=12,
        speed=40,
        initiative_mod=1,
        passive_perception=10,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 2, "dex": 1, "con": 1, "int": -4, "wis": 0, "cha": -3},
        trait_ids=(),
        attacks={
            "bite": AttackExpectation(
                kind="melee",
                attack_bonus=4,
                ability_modifier=2,
                damage_modifier=2,
                damage_type="piercing",
                damage_dice=((1, 8),),
            )
        },
        opening_weapon_id="bite",
        melee_fallback_weapon_id="bite",
        special_mechanics=(),
        benchmark_preset_id="giant_lizard_benchmark",
        benchmark_count=5,
    ),
    "violet_fungus": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=18,
        ac=5,
        speed=5,
        initiative_mod=-5,
        passive_perception=6,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": -4, "dex": -5, "con": 0, "int": -5, "wis": -4, "cha": -5},
        trait_ids=(),
        attacks={
            "rotting_touch": AttackExpectation(
                kind="melee",
                attack_bonus=2,
                ability_modifier=-4,
                damage_modifier=0,
                damage_type="necrotic",
                reach=10,
                damage_dice=((1, 8),),
            )
        },
        opening_weapon_id="rotting_touch",
        melee_fallback_weapon_id="rotting_touch",
        special_mechanics=("multiattack",),
        benchmark_preset_id="violet_fungus_benchmark",
        benchmark_count=6,
    ),
    "polar_bear": MonsterExpectation(
        ai_profile_id="melee_brute",
        max_hp=42,
        ac=12,
        speed=40,
        initiative_mod=2,
        passive_perception=15,
        size_category="large",
        footprint=(2, 2),
        ability_mods={"str": 5, "dex": 2, "con": 3, "int": -4, "wis": 1, "cha": -2},
        trait_ids=(),
        attacks={
            "rend": AttackExpectation(
                kind="melee",
                attack_bonus=7,
                ability_modifier=5,
                damage_modifier=5,
                damage_type="slashing",
                damage_dice=((1, 8),),
            )
        },
        opening_weapon_id="rend",
        melee_fallback_weapon_id="rend",
        special_mechanics=("multiattack",),
        benchmark_preset_id="polar_bear_benchmark",
        benchmark_count=2,
        damage_resistances=("cold",),
    ),
    "guard_captain": MonsterExpectation(
        ai_profile_id="ranged_skirmisher",
        max_hp=75,
        ac=18,
        speed=30,
        initiative_mod=4,
        passive_perception=14,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 4, "dex": 2, "con": 3, "int": 1, "wis": 2, "cha": 1},
        trait_ids=(),
        attacks={
            "longsword": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="slashing",
                damage_dice=((2, 10),),
            ),
            "javelin": AttackExpectation(
                kind="melee",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="piercing",
                damage_dice=((3, 6),),
            ),
            "javelin_throw": AttackExpectation(
                kind="ranged",
                attack_bonus=6,
                ability_modifier=4,
                damage_modifier=4,
                damage_type="piercing",
                range=(30, 120),
                damage_dice=((3, 6),),
            ),
        },
        opening_weapon_id="javelin_throw",
        melee_fallback_weapon_id="longsword",
        special_mechanics=("multiattack", "parry"),
        benchmark_preset_id="guard_captain_benchmark",
        benchmark_count=1,
        reaction_ids=("opportunity_attack", "parry"),
    ),
    "warrior_veteran": MonsterExpectation(
        ai_profile_id="line_holder",
        max_hp=65,
        ac=17,
        speed=30,
        initiative_mod=3,
        passive_perception=12,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 3, "dex": 1, "con": 2, "int": 0, "wis": 0, "cha": 0},
        trait_ids=(),
        attacks={
            "greatsword": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=3,
                damage_type="slashing",
                damage_dice=((2, 6),),
            ),
            "heavy_crossbow": AttackExpectation(
                kind="ranged",
                attack_bonus=3,
                ability_modifier=1,
                damage_modifier=1,
                damage_type="piercing",
                range=(100, 400),
                damage_dice=((2, 10),),
            ),
        },
        opening_weapon_id="greatsword",
        melee_fallback_weapon_id="greatsword",
        special_mechanics=("multiattack", "parry"),
        benchmark_preset_id="warrior_veteran_benchmark",
        benchmark_count=2,
        reaction_ids=("opportunity_attack", "parry"),
    ),
    "knight": MonsterExpectation(
        ai_profile_id="line_holder",
        max_hp=52,
        ac=18,
        speed=30,
        initiative_mod=0,
        passive_perception=10,
        size_category="medium",
        footprint=(1, 1),
        ability_mods={"str": 3, "dex": 0, "con": 2, "int": 0, "wis": 0, "cha": 2},
        trait_ids=(),
        attacks={
            "greatsword": AttackExpectation(
                kind="melee",
                attack_bonus=5,
                ability_modifier=3,
                damage_modifier=0,
                damage_type=None,
                damage_components=(
                    DamageComponentExpectation("slashing", ((2, 6),), 3),
                    DamageComponentExpectation("radiant", ((1, 8),), 0),
                ),
            ),
            "heavy_crossbow": AttackExpectation(
                kind="ranged",
                attack_bonus=2,
                ability_modifier=0,
                damage_modifier=0,
                damage_type=None,
                range=(100, 400),
                damage_components=(
                    DamageComponentExpectation("piercing", ((2, 10),), 0),
                    DamageComponentExpectation("radiant", ((1, 8),), 0),
                ),
            ),
        },
        opening_weapon_id="greatsword",
        melee_fallback_weapon_id="greatsword",
        special_mechanics=("multiattack", "parry"),
        benchmark_preset_id="knight_benchmark",
        benchmark_count=2,
        reaction_ids=("opportunity_attack", "parry"),
        condition_immunities=("frightened",),
    ),
}

REMAINING_MONSTER_IDS: tuple[str, ...] = tuple(MONSTER_EXPECTATIONS)
RANGED_SKIRMISHER_MONSTER_IDS: tuple[str, ...] = tuple(
    monster_id
    for monster_id, expectation in MONSTER_EXPECTATIONS.items()
    if expectation.ai_profile_id == "ranged_skirmisher"
)
PACK_TACTICS_MONSTER_IDS: tuple[str, ...] = tuple(
    monster_id
    for monster_id, expectation in MONSTER_EXPECTATIONS.items()
    if "pack_tactics" in expectation.special_mechanics
)
LARGE_MONSTER_IDS: tuple[str, ...] = tuple(
    monster_id for monster_id, expectation in MONSTER_EXPECTATIONS.items() if expectation.footprint == (2, 2)
)
MULTI_SQUARE_MONSTER_IDS: tuple[str, ...] = tuple(
    monster_id for monster_id, expectation in MONSTER_EXPECTATIONS.items() if expectation.footprint != (1, 1)
)
MELEE_ONLY_MONSTER_IDS: tuple[str, ...] = tuple(
    monster_id
    for monster_id, expectation in MONSTER_EXPECTATIONS.items()
    if all(attack.kind == "melee" for attack in expectation.attacks.values())
)
