from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from backend.engine.models.state import DiceSpec


@dataclass(frozen=True)
class SpellDefinition:
    """Static combat spell content entry for the live simulator."""

    spell_id: str
    display_name: str
    level: int
    school: str
    description: str
    timing: Literal["action", "bonus_action", "reaction"]
    targeting_mode: Literal[
        "ranged_spell_attack",
        "melee_spell_attack",
        "multi_ray_spell_attack",
        "auto_hit_single_target",
        "reaction_self",
        "smite_trigger",
        "self_cone_save",
        "multi_ally_buff",
        "touch_heal",
        "self_ac_buff",
        "self_temp_hp",
        "multi_ally_hp_buff",
        "touch_speed_buff",
        "ranged_ally_ac_buff",
        "single_target_save",
        "multi_target_save",
        "self_weapon_damage_buff",
        "touch_heroism_buff",
        "ranged_ally_haste_buff",
        "point_sphere_save",
        "multi_target_command",
        "reaction_counterspell",
        "metadata_only",
    ]
    range_feet: int
    damage_dice: tuple[DiceSpec, ...]
    damage_modifier: int
    damage_type: str
    attack_ability: str | None = None
    save_ability: str | None = None
    half_on_success: bool = False
    on_hit_effect_kind: Literal["no_reactions", "slow", "healing_blocked", "poisoned_save"] | None = None
    ac_bonus: int = 0
    negates_magic_missile: bool = False
    concentration: bool = False
    duration_rounds: int = 0
    max_targets: int = 1
    target_cluster_feet: int = 5
    healing_dice: tuple[DiceSpec, ...] = ()
    healing_modifier_ability: str | None = None
    temporary_hit_point_dice: tuple[DiceSpec, ...] = ()
    temporary_hit_point_modifier: int = 0
    hp_bonus: int = 0
    speed_bonus: int = 0
    speed_multiplier: int = 1
    speed_penalty: int = 0
    save_advantage_abilities: tuple[str, ...] = ()
    selectable_damage_types: tuple[str, ...] = ()
    radius_feet: int = 0
    ray_count: int = 1
    command_word: str | None = None
    upcast_target_counts: dict[int, int] = field(default_factory=dict)


SPELL_DEFINITIONS: dict[str, SpellDefinition] = {
    "fire_bolt": SpellDefinition(
        spell_id="fire_bolt",
        display_name="Fire Bolt",
        level=0,
        school="evocation",
        description="Ranged spell attack dealing fire damage.",
        timing="action",
        targeting_mode="ranged_spell_attack",
        range_feet=120,
        damage_dice=(DiceSpec(count=1, sides=10),),
        damage_modifier=0,
        damage_type="fire",
        attack_ability="int",
    ),
    "shocking_grasp": SpellDefinition(
        spell_id="shocking_grasp",
        display_name="Shocking Grasp",
        level=0,
        school="evocation",
        description="Melee spell attack dealing lightning damage and suppressing reactions on a hit.",
        timing="action",
        targeting_mode="melee_spell_attack",
        range_feet=5,
        damage_dice=(DiceSpec(count=1, sides=8),),
        damage_modifier=0,
        damage_type="lightning",
        attack_ability="int",
        on_hit_effect_kind="no_reactions",
    ),
    "ray_of_frost": SpellDefinition(
        spell_id="ray_of_frost",
        display_name="Ray of Frost",
        level=0,
        school="evocation",
        description="Ranged spell attack dealing cold damage and slowing the target on a hit.",
        timing="action",
        targeting_mode="ranged_spell_attack",
        range_feet=60,
        damage_dice=(DiceSpec(count=1, sides=8),),
        damage_modifier=0,
        damage_type="cold",
        attack_ability="int",
        on_hit_effect_kind="slow",
        speed_penalty=10,
    ),
    "chill_touch": SpellDefinition(
        spell_id="chill_touch",
        display_name="Chill Touch",
        level=0,
        school="necromancy",
        description="Ranged spell attack dealing necrotic damage and preventing healing on a hit.",
        timing="action",
        targeting_mode="ranged_spell_attack",
        range_feet=120,
        damage_dice=(DiceSpec(count=1, sides=8),),
        damage_modifier=0,
        damage_type="necrotic",
        attack_ability="int",
        on_hit_effect_kind="healing_blocked",
    ),
    "poison_spray": SpellDefinition(
        spell_id="poison_spray",
        display_name="Poison Spray",
        level=0,
        school="necromancy",
        description="Single-target cantrip forcing a Constitution save against poison damage.",
        timing="action",
        targeting_mode="single_target_save",
        range_feet=30,
        damage_dice=(DiceSpec(count=1, sides=12),),
        damage_modifier=0,
        damage_type="poison",
        attack_ability="int",
        save_ability="con",
        half_on_success=False,
    ),
    "acid_splash": SpellDefinition(
        spell_id="acid_splash",
        display_name="Acid Splash",
        level=0,
        school="evocation",
        description="Cantrip forcing one or two nearby creatures to make Dexterity saves against acid damage.",
        timing="action",
        targeting_mode="multi_target_save",
        range_feet=60,
        damage_dice=(DiceSpec(count=1, sides=6),),
        damage_modifier=0,
        damage_type="acid",
        attack_ability="int",
        save_ability="dex",
        half_on_success=False,
        max_targets=2,
    ),
    "magic_missile": SpellDefinition(
        spell_id="magic_missile",
        display_name="Magic Missile",
        level=1,
        school="evocation",
        description="Auto-hit force darts that can be directed at one creature or several.",
        timing="action",
        targeting_mode="auto_hit_single_target",
        range_feet=120,
        damage_dice=(DiceSpec(count=3, sides=4),),
        damage_modifier=3,
        damage_type="force",
    ),
    "chromatic_orb": SpellDefinition(
        spell_id="chromatic_orb",
        display_name="Chromatic Orb",
        level=1,
        school="evocation",
        description="Ranged spell attack dealing 3d8 damage of a selected elemental type.",
        timing="action",
        targeting_mode="ranged_spell_attack",
        range_feet=90,
        damage_dice=(DiceSpec(count=3, sides=8),),
        damage_modifier=0,
        damage_type="acid",
        attack_ability="int",
        selectable_damage_types=("acid", "cold", "fire", "lightning", "poison", "thunder"),
    ),
    "ray_of_sickness": SpellDefinition(
        spell_id="ray_of_sickness",
        display_name="Ray of Sickness",
        level=1,
        school="necromancy",
        description="Ranged spell attack dealing poison damage, then forcing a Constitution save or poisoning the target.",
        timing="action",
        targeting_mode="ranged_spell_attack",
        range_feet=60,
        damage_dice=(DiceSpec(count=2, sides=8),),
        damage_modifier=0,
        damage_type="poison",
        attack_ability="int",
        save_ability="con",
        on_hit_effect_kind="poisoned_save",
        duration_rounds=1,
    ),
    "shield": SpellDefinition(
        spell_id="shield",
        display_name="Shield",
        level=1,
        school="abjuration",
        description="Reaction spell that grants +5 AC and blocks Magic Missile until the next turn start.",
        timing="reaction",
        targeting_mode="reaction_self",
        range_feet=0,
        damage_dice=(),
        damage_modifier=0,
        damage_type="force",
        ac_bonus=5,
        negates_magic_missile=True,
    ),
    "burning_hands": SpellDefinition(
        spell_id="burning_hands",
        display_name="Burning Hands",
        level=1,
        school="evocation",
        description="Self-origin fire cone forcing Dexterity saves for half damage.",
        timing="action",
        targeting_mode="self_cone_save",
        range_feet=15,
        damage_dice=(DiceSpec(count=3, sides=6),),
        damage_modifier=0,
        damage_type="fire",
        save_ability="dex",
        half_on_success=True,
    ),
    "bless": SpellDefinition(
        spell_id="bless",
        display_name="Bless",
        level=1,
        school="enchantment",
        description="Concentration prayer that adds 1d4 to attack rolls and saving throws for up to three allies.",
        timing="action",
        targeting_mode="multi_ally_buff",
        range_feet=30,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        concentration=True,
        duration_rounds=10,
        max_targets=3,
    ),
    "cure_wounds": SpellDefinition(
        spell_id="cure_wounds",
        display_name="Cure Wounds",
        level=1,
        school="abjuration",
        description="Touch-range healing spell restoring 2d8 plus the caster's spellcasting modifier.",
        timing="action",
        targeting_mode="touch_heal",
        range_feet=5,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        healing_dice=(DiceSpec(count=2, sides=8),),
        healing_modifier_ability="spellcasting",
    ),
    "aid": SpellDefinition(
        spell_id="aid",
        display_name="Aid",
        level=2,
        school="abjuration",
        description="Non-concentration support magic that increases current and maximum HP for up to three allies.",
        timing="action",
        targeting_mode="multi_ally_hp_buff",
        range_feet=30,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        duration_rounds=4800,
        max_targets=3,
        hp_bonus=5,
    ),
    "mage_armor": SpellDefinition(
        spell_id="mage_armor",
        display_name="Mage Armor",
        level=1,
        school="abjuration",
        description="Self-only abjuration that sets base AC to 13 + Dexterity modifier when better.",
        timing="action",
        targeting_mode="self_ac_buff",
        range_feet=0,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        concentration=False,
        duration_rounds=4800,
    ),
    "false_life": SpellDefinition(
        spell_id="false_life",
        display_name="False Life",
        level=1,
        school="necromancy",
        description="Self-only necromancy spell granting 2d4 + 4 temporary hit points.",
        timing="action",
        targeting_mode="self_temp_hp",
        range_feet=0,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        concentration=False,
        duration_rounds=600,
        temporary_hit_point_dice=(DiceSpec(count=2, sides=4),),
        temporary_hit_point_modifier=4,
    ),
    "longstrider": SpellDefinition(
        spell_id="longstrider",
        display_name="Longstrider",
        level=1,
        school="transmutation",
        description="Touch-range transmutation spell granting a non-stacking 10-foot speed bonus.",
        timing="action",
        targeting_mode="touch_speed_buff",
        range_feet=5,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        concentration=False,
        duration_rounds=600,
        speed_bonus=10,
    ),
    "shield_of_faith": SpellDefinition(
        spell_id="shield_of_faith",
        display_name="Shield of Faith",
        level=1,
        school="abjuration",
        description="Bonus-action concentration spell granting a willing ally +2 AC.",
        timing="bonus_action",
        targeting_mode="ranged_ally_ac_buff",
        range_feet=60,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        ac_bonus=2,
        concentration=True,
        duration_rounds=100,
    ),
    "heroism": SpellDefinition(
        spell_id="heroism",
        display_name="Heroism",
        level=1,
        school="enchantment",
        description="Touch-range concentration spell granting start-of-turn temporary HP and frightened immunity.",
        timing="action",
        targeting_mode="touch_heroism_buff",
        range_feet=5,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        concentration=True,
        duration_rounds=10,
    ),
    "divine_favor": SpellDefinition(
        spell_id="divine_favor",
        display_name="Divine Favor",
        level=1,
        school="evocation",
        description="Bonus-action concentration spell adding 1d4 radiant damage to the caster's weapon attacks.",
        timing="bonus_action",
        targeting_mode="self_weapon_damage_buff",
        range_feet=0,
        damage_dice=(DiceSpec(count=1, sides=4),),
        damage_modifier=0,
        damage_type="radiant",
        concentration=True,
        duration_rounds=10,
    ),
    "shatter": SpellDefinition(
        spell_id="shatter",
        display_name="Shatter",
        level=2,
        school="evocation",
        description="Area thunder burst forcing Constitution saves for half damage.",
        timing="action",
        targeting_mode="multi_target_save",
        range_feet=60,
        damage_dice=(DiceSpec(count=3, sides=8),),
        damage_modifier=0,
        damage_type="thunder",
        attack_ability="int",
        save_ability="con",
        half_on_success=True,
        max_targets=8,
        target_cluster_feet=10,
    ),
    "scorching_ray": SpellDefinition(
        spell_id="scorching_ray",
        display_name="Scorching Ray",
        level=2,
        school="evocation",
        description="Ranged spell attack that creates three fire rays.",
        timing="action",
        targeting_mode="multi_ray_spell_attack",
        range_feet=120,
        damage_dice=(DiceSpec(count=2, sides=6),),
        damage_modifier=0,
        damage_type="fire",
        attack_ability="spellcasting",
        ray_count=3,
    ),
    "fireball": SpellDefinition(
        spell_id="fireball",
        display_name="Fireball",
        level=3,
        school="evocation",
        description="Point-origin fiery sphere forcing Dexterity saves for half damage.",
        timing="action",
        targeting_mode="point_sphere_save",
        range_feet=150,
        radius_feet=20,
        damage_dice=(DiceSpec(count=8, sides=6),),
        damage_modifier=0,
        damage_type="fire",
        save_ability="dex",
        half_on_success=True,
    ),
    "counterspell": SpellDefinition(
        spell_id="counterspell",
        display_name="Counterspell",
        level=3,
        school="abjuration",
        description="Reaction spell that interrupts a hostile leveled spell cast within 60 feet.",
        timing="reaction",
        targeting_mode="reaction_counterspell",
        range_feet=60,
        damage_dice=(),
        damage_modifier=0,
        damage_type="",
    ),
    "haste": SpellDefinition(
        spell_id="haste",
        display_name="Haste",
        level=3,
        school="transmutation",
        description="Concentration transmutation granting +2 AC, doubled speed, Dexterity save advantage, and one restricted extra action.",
        timing="action",
        targeting_mode="ranged_ally_haste_buff",
        range_feet=30,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        ac_bonus=2,
        speed_multiplier=2,
        save_advantage_abilities=("dex",),
        concentration=True,
        duration_rounds=10,
    ),
    "command": SpellDefinition(
        spell_id="command",
        display_name="Command",
        level=1,
        school="enchantment",
        description="Single-word command forcing a Wisdom save.",
        timing="action",
        targeting_mode="multi_target_command",
        range_feet=60,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        save_ability="wis",
        command_word="flee",
        max_targets=1,
        upcast_target_counts={2: 2},
    ),
    "detect_magic": SpellDefinition(
        spell_id="detect_magic",
        display_name="Detect Magic",
        level=1,
        school="divination",
        description="Utility detection spell recorded as metadata only in combat.",
        timing="action",
        targeting_mode="metadata_only",
        range_feet=0,
        damage_dice=(),
        damage_modifier=0,
        damage_type="none",
        concentration=True,
        duration_rounds=100,
    ),
    "divine_smite": SpellDefinition(
        spell_id="divine_smite",
        display_name="Divine Smite",
        level=1,
        school="evocation",
        description="Bonus-action smite after a melee hit, adding radiant damage to the attack.",
        timing="bonus_action",
        targeting_mode="smite_trigger",
        range_feet=0,
        damage_dice=(DiceSpec(count=2, sides=8),),
        damage_modifier=0,
        damage_type="radiant",
    ),
}


def get_spell_definition(spell_id: str) -> SpellDefinition:
    try:
        return SPELL_DEFINITIONS[spell_id]
    except KeyError as error:
        raise ValueError(f"Unknown spell definition '{spell_id}'.") from error
